### ISSUE TITLE
Collection.json cannot be resolved

### ISSUE THREAD

**Issue by JadsonSouzaPG** [scullyio/scully#1269]
### Description
When trying to install Scully on a new angular project, the error is returned after installing packages:

`Installing packages for tooling via npm.
Installed packages for tooling via npm.
An unhandled exception occurred: Collection "/home/jadson/Naza/angular10blog/node_modules/@scullyio/init/src/collection.json" cannot be resolved.
See "/tmp/ng-lMzMY4/angular-errors.log" for further details.
`

#### 🔬 Minimal Reproduction
<pre><code>
ng new angular10blog
ng add @scullyio/init

Installing packages for tooling via npm.
Installed packages for tooling via npm.
An unhandled exception occurred: Collection "/home/jadson/Naza/angular10blog/node_modules/@scullyio/init/src/collection.json" cannot be resolved.
See "/tmp/ng-lMzMY4/angular-errors.log" for further details.

</code></pre>
#### 💻Your Environment

**Angular Version:**

<pre><code>

10.2.4

</code></pre>

**Scully Version:**

<pre><code>

1.1.0

</code></pre>

## 🔥 Exception or Error

<pre><code>

[error] Error: Collection "/home/jadson/Naza/angular10blog/node_modules/@scullyio/init/src/collection.json" cannot be resolved.
    at NodeModulesEngineHost.resolve (/home/jadson/Naza/angular10blog/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:75:19)
    at NodeModulesEngineHost.resolve (/home/jadson/Naza/angular10blog/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:55:35)
    at NodeModulesEngineHost._resolveCollectionPath (/home/jadson/Naza/angular10blog/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:80:37)
    at NodeModulesEngineHost.createCollectionDescription (/home/jadson/Naza/angular10blog/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:111:27)
    at SchematicEngine._createCollectionDescription (/home/jadson/Naza/angular10blog/node_modules/@angular-devkit/schematics/src/engine/engine.js:148:40)
    at SchematicEngine.createCollection (/home/jadson/Naza/angular10blog/node_modules/@angular-devkit/schematics/src/engine/engine.js:141:43)
    at AddCommand.getCollection (/home/jadson/Naza/angular10blog/node_modules/@angular/cli/models/schematic-command.js:128:35)
    at AddCommand.runSchematic (/home/jadson/Naza/angular10blog/node_modules/@angular/cli/models/schematic-command.js:298:50)
    at AddCommand.executeSchematic (/home/jadson/Naza/angular10blog/node_modules/@angular/cli/commands/add-impl.js:186:31)
    at AddCommand.run (/home/jadson/Naza/angular10blog/node_modules/@angular/cli/commands/add-impl.js:152:21)
    at async AddCommand.validateAndRun (/home/jadson/Naza/angular10blog/node_modules/@angular/cli/models/command.js:134:28)
    at async Object.runCommand (/home/jadson/Naza/angular10blog/node_modules/@angular/cli/models/command-runner.js:198:24)
    at async default_1 (/home/jadson/Naza/angular10blog/node_modules/@angular/cli/lib/cli/index.js:59:31)
</code></pre>

**Comment by SanderElias** [comment]
@jorgeucano Can you check the new schematics for this?

**Comment by billolo1** [comment]
Doubling down on this issue with both angular and nx workspaces

**Comment by SanderElias** [comment]
Closing this issue as its resolved by releasing schematics 1.1.1.
