### ISSUE TITLE
scully-plugin-flash : Cannot find module

### ISSUE THREAD

**Issue by AbbaciKhaled** [scullyio/scully#1384]
### Description

I installed the scully-plugin-flash by following the steps mentioned in the official documentation, the problem is that when I try to run the scully command, it shows me the following error message (while the package is located in node_modules) : 

#### 💻Your Environment

**Angular Version:**
Angular CLI: 11.1.4
Node: 14.15.5
OS: win32 x64

<pre><code>
 / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 11.1.4
Node: 14.15.5
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1101.4 (cli-only)
@angular-devkit/core         11.1.4 (cli-only)
@angular-devkit/schematics   11.1.4 (cli-only)
@schematics/angular          11.1.4 (cli-only)
@schematics/update           0.1101.4 (cli-only)
</code></pre>

**Scully Version:**

<pre><code>
"@scullyio/init": "^1.0.1",
"@scullyio/ng-lib": "^1.1.0",
"@scullyio/scully": "^1.1.1",
</code></pre>

## 🔥 Exception or Error

<pre><code>
---------
 We encountered an error executing the config file. ".\scully.logone.config.ts"
 Check the error below, and try again later
--------- 
Error: Cannot find module 'scully-plugin-flash-prevention'
Require stack:
- E:\Projets\Izeelogo\Website\scully.logone.config.js
- E:\Projets\Izeelogo\Website\node_modules\@scullyio\scully\src\lib\utils\compileConfig.js
- E:\Projets\Izeelogo\Website\node_modules\@scullyio\scully\src\lib\utils\config.js
- E:\Projets\Izeelogo\Website\node_modules\@scullyio\scully\src\lib\renderPlugins\launchedBrowser.js
- E:\Projets\Izeelogo\Website\node_modules\@scullyio\scully\src\lib\utils\handlers\defaultAction.js
- E:\Projets\Izeelogo\Website\node_modules\@scullyio\scully\src\lib\utils\handlers\index.js
- E:\Projets\Izeelogo\Website\node_modules\@scullyio\scully\src\lib\utils\index.js
- E:\Projets\Izeelogo\Website\node_modules\@scullyio\scully\src\lib\fileHanderPlugins\asciidoc.js
- E:\Projets\Izeelogo\Website\node_modules\@scullyio\scully\src\lib\pluginManagement\systemPlugins.js
- E:\Projets\Izeelogo\Website\node_modules\@scullyio\scully\src\scully.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (E:\Projets\Izeelogo\Website\scully.logone.config.js:4:32)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'E:\\Projets\\Izeelogo\\Website\\scully.logone.config.js',
    'E:\\Projets\\Izeelogo\\Website\\node_modules\\@scullyio\\scully\\src\\lib\\utils\\compileConfig.js',
    'E:\\Projets\\Izeelogo\\Website\\node_modules\\@scullyio\\scully\\src\\lib\\utils\\config.js',
    'E:\\Projets\\Izeelogo\\Website\\node_modules\\@scullyio\\scully\\src\\lib\\renderPlugins\\launchedBrowser.js',
    'E:\\Projets\\Izeelogo\\Website\\node_modules\\@scullyio\\scully\\src\\lib\\utils\\handlers\\defaultAction.js',
    'E:\\Projets\\Izeelogo\\Website\\node_modules\\@scullyio\\scully\\src\\lib\\utils\\handlers\\index.js',
    'E:\\Projets\\Izeelogo\\Website\\node_modules\\@scullyio\\scully\\src\\lib\\utils\\index.js',
    'E:\\Projets\\Izeelogo\\Website\\node_modules\\@scullyio\\scully\\src\\lib\\fileHanderPlugins\\asciidoc.js',
    'E:\\Projets\\Izeelogo\\Website\\node_modules\\@scullyio\\scully\\src\\lib\\pluginManagement\\systemPlugins.js',
    'E:\\Projets\\Izeelogo\\Website\\node_modules\\@scullyio\\scully\\src\\scully.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 15
npm ERR! logone@0.0.0 scully: `scully`
npm ERR! Exit status 15
npm ERR!
npm ERR! Failed at the logone@0.0.0 scully script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PC Gamer\AppData\Roaming\npm-cache\_logs\2021-06-05T15_21_33_291Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 15
npm ERR! logone@0.0.0 csr: `ng build --prod --buildOptimizer=true && npm run scully`
npm ERR! Exit status 15
npm ERR!
npm ERR! Failed at the logone@0.0.0 csr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PC Gamer\AppData\Roaming\npm-cache\_logs\2021-06-05T15_21_33_332Z-debug.log
</code></pre>

**Comment by AbbaciKhaled** [comment]
You need to import '@scullyio/scully-plugin-flash-prevention' instead of 

'scully-plugin-flash-prevention' (which is written in the official documentation)
