### ISSUE TITLE
scully isn't generating all the routes

### ISSUE THREAD

**Issue by mhamri** [scullyio/scully#1599]
### Description

I have a very simple two page website, but i'm using nx to maintain it 

here is my `app.module.ts`

```
const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'privacy', component: PrivacyComponent },
];

@NgModule({
  declarations: [AppComponent, PrivacyComponent, HomeComponent],
  imports: [
    BrowserModule,
    ScullyLibModule,
    RouterModule.forRoot(routes),
    DeskiHeroBanner6ComponentModule,
    DeskiFooterStyle6ComponentModule,
    DeskiWrapperModule,
  ],
  providers: [],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

and it's my scully config 

```
import { ScullyConfig } from '@scullyio/scully';

/** this loads the default render plugin, remove when switching to something else. */
import '@scullyio/scully-plugin-puppeteer';

export const config: ScullyConfig = {
  projectRoot: './apps/axumrei-website/src',
  projectName: 'axumrei-website',
  // add spsModulePath when using de Scully Platform Server,
  outDir: './dist/static',
  routes: {
    // '/privacy': {
    //   type: 'ignored',
    // },
  },
  target: 'targets',
};
```

if I run the `nx g @scullyio/init:route-discovery` i get this 

```
[ '', '/privacy' ]
the  exist.
the /privacy exist.
import { ScullyConfig } from '@scullyio/scully';

/** this loads the default render plugin, remove when switching to something else. */
import '@scullyio/scully-plugin-puppeteer';

export const config: ScullyConfig = {
  projectRoot: './apps/axumrei-website/src',
  projectName: 'axumrei-website',
  // add spsModulePath when using de Scully Platform Server,
  outDir: './dist/static',
  routes: {
    // '/privacy': {
    //   type: 'ignored',
    // },
  },
  target: 'targets',
};

UPDATE scully.axumrei-website.config.ts
```

i assume the 3rd line means it already knows about the privacy path.

then if I run `nx g @scullyio/init:scully`

i get this error 

```
>  NX  Generating @scullyio/init:scully

SchematicsException [Error]: There is no undefined project in angular.json
    at C:\repo\TentCodeProjects\TentCode\frontend2\node_modules\@scullyio\init\src\scully\index.js:36:15
    at MergeMapSubscriber.project (C:\repo\TentCodeProjects\TentCode\frontend2\node_modules\@angular-devkit\schematics\src\rules\call.js:75:24)        
    at MergeMapSubscriber._tryNext (C:\repo\TentCodeProjects\TentCode\frontend2\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\mergeMap.js:67:27)
    at MergeMapSubscriber._next (C:\repo\TentCodeProjects\TentCode\frontend2\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (C:\repo\TentCodeProjects\TentCode\frontend2\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (C:\repo\TentCodeProjects\TentCode\frontend2\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\mergeMap.js:93:26)
    at SimpleInnerSubscriber._next (C:\repo\TentCodeProjects\TentCode\frontend2\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\innerSubscribe.js:27:21)
    at SimpleInnerSubscriber.Subscriber.next (C:\repo\TentCodeProjects\TentCode\frontend2\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Subscriber.js:66:18)
    at Observable._subscribe (C:\repo\TentCodeProjects\TentCode\frontend2\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\util\subscribeToArray.js:5:20)
    at Observable._trySubscribe (C:\repo\TentCodeProjects\TentCode\frontend2\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Observable.js:44:25)
There is no undefined project in angular.json
```
I assume this one still doesn't support nx yet. 

then i'm calling `npx scully --cf scully.axumrei-website.config.ts` to generate the static files which output like this 

```
❯ npx scully --cf scully.axumrei-website.config.ts
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
  ✔ Folder "./scully" used for custom plugins
scully: using project config from "undefined"
  ✔ new Angular build files imported
```

but after scully is done, I don't see any folder for privacy

![image](https://user-images.githubusercontent.com/8991783/176911490-afab66c6-cc62-45a4-81c8-de1e4c99dc2f.png)

these are some of the other variant that I've tried 
```
npx scully  --RSD --ls normal //-> this one warn about can't find project and use --project 

npx scully  --RSD --ls normal --project=axumrei-website --pjFirst
npx scully  --RSD --ls normal --project axumrei-website --pjFirst

npx scully --cf scully.axumrei-website.config.ts --RSD --ls normal
npx scully --cf scully.axumrei-website.config.ts --project axumrei-website


```

almost all of them has this output 
```
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
  ✔ Folder "./scully" used for custom plugins
scully: using project config from "undefined"
  ✔ .\dist\static folder successfully cleaned
  ✔ new Angular build files imported
  ✔ copied index.html to 404.html
```
#### 🔬 Minimal Reproduction
I don't have atm
#### 💻Your Environment

**Angular Version:**

<pre><code>

❯ ng --version
Workspace config file cannot be loaded: C:\repo\TentCodeProjects\TentCode\frontend2\angular.json
Invalid format version detected - Expected:[ 1 ] Found: [ 2 ]
⨯ amrim@REKAB  C:\repo\TentCodeProjects\TentCode\frontend2   master ↑7 +9 ~9 -0 !                                                         [22:15]
❯ npx ng --version
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
14.3.6
</code></pre>

**Scully Version:**

<pre><code>

{
  "name": "frontend2",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "nx",
    "postinstall": "node ./decorate-angular-cli.js && ngcc --properties es2020 browser module main",
    "start": "nx serve",
    "build": "nx build",
    "test": "nx test",
    "scully": "npx scully --",
    "scully:axumrei": "npx scully serve --project axumrei-website",
    "scully:axumrei:build": "npm run pwsh -- \"rm -R -Force -ErrorAction Ignore  dist || & { $global:LASTEXITCODE = 0 }\" && npm run build && npx scully --project axumrei-website && npm run pwsh -- \"Compress-Archive -Path dist/static/* -DestinationPath dist/axumrei.zip\" ",
    "pwsh": "pwsh -NoProfile  -c",
    "dir": "npm run zip -- ls",
    "scully:serve": "npx scully serve --"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "14.0.2",
    "@angular/common": "14.0.2",
    "@angular/compiler": "14.0.2",
    "@angular/core": "14.0.2",
    "@angular/forms": "14.0.2",
    "@angular/platform-browser": "14.0.2",
    "@angular/platform-browser-dynamic": "14.0.2",
    "@angular/platform-server": "^14.0.2",
    "@angular/router": "14.0.2",
    "@nrwl/angular": "14.3.6",
    "@scullyio/ng-lib": "^2.1.36",
    "@scullyio/platform-server": "^2.1.36",
    "@scullyio/scully": "^2.1.36",
    "@scullyio/scully-plugin-puppeteer": "^2.1.36",
    "rxjs": "~7.4.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "14.0.2",
    "@angular-eslint/eslint-plugin": "13.5.0",
    "@angular-eslint/eslint-plugin-template": "13.5.0",
    "@angular-eslint/template-parser": "13.5.0",
    "@angular/cli": "~14.0.2",
    "@angular/compiler-cli": "14.0.2",
    "@angular/language-service": "14.0.2",
    "@nrwl/cli": "14.3.6",
    "@nrwl/cypress": "14.3.6",
    "@nrwl/eslint-plugin-nx": "14.3.6",
    "@nrwl/jest": "14.3.6",
    "@nrwl/linter": "14.3.6",
    "@nrwl/workspace": "14.3.6",
    "@scullyio/init": "^2.1.36",
    "@types/jest": "27.4.1",
    "@types/node": "16.11.7",
    "@typescript-eslint/eslint-plugin": "5.28.0",
    "@typescript-eslint/parser": "5.28.0",
    "cypress": "^9.1.0",
    "eslint": "8.18.0",
    "eslint-config-prettier": "8.5.0",
    "eslint-plugin-cypress": "^2.12.1",
    "jest": "27.5.1",
    "jest-preset-angular": "11.1.2",
    "nx": "14.3.6",
    "prettier": "2.7.1",
    "ts-jest": "27.1.4",
    "typescript": "4.7.4"
  }
}
</code></pre>

**Comment by mhamri** [comment]
it's a minimal setup 
https://github.com/mhamri/scully-route-bug

**Comment by nelsongutidev** [comment]
Can you try adding the `defaultProject` property on the angular.json file with your project's name?

Example: 

`"defaultProject": "your-project-name"`
