### ISSUE TITLE
projectRoot missing in "scully.json" due to fs_extra_1.pathExists is not a function

### ISSUE THREAD

**Issue by Splaktar** [scullyio/scully#28]
# Steps to Reproduce
1. `ng add @scullyio/init`
1. `ng build`
1. `npm run scully`

# Error

```sh
npm run scully

TypeError: fs_extra_1.pathExists is not a function
    at Object.exports.compileConfig (/Users/splaktar/Git/.../node_modules/@scullyio/scully/bin/utils/compileConfig.js:15:32)
    at loadIt (/Users/splaktar/Git/.../node_modules/@scullyio/scully/bin/utils/config.js:15:50)
    at Object.<anonymous> (/Users/splaktar/Git/.../node_modules/@scullyio/scully/bin/utils/config.js:50:22)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/splaktar/Git/.../node_modules/@scullyio/scully/bin/routerPlugins/contentFolderPlugin.js:6:18)
projectRoot missing in "scully.json"
No routes defined in "scully.config"
```
Looking at my **`scully.config.js`** file:
```js
exports.config = {
  projectRoot: "./src/app",
  routes: {
  }
};
```
The `projectRoot` is defined and seems to be correct for my repo.

Since I don't have any routes that have params, do I need to define `routes: {}` in `scully.config.js`?

The error message seems to be referring to the wrong file name? `scully.json`

**Comment by Splaktar** [comment]
In my `AppModule`, I have the following
```ts
import {AppRoutes} from './app-routes';
...
RouterModule.forRoot(AppRoutes),
```
In `app-routes.ts`, I have the following:
```ts
import {Routes} from '@angular/router';
import {AboutComponent} from './about/about.component';
import {PageNotFoundComponent} from './page-not-found/page-not-found.component';

export const AppRoutes: Routes = [
  {
    path: '',
    pathMatch: 'full',
    component: AboutComponent,
    children: []
  },
  {path: '**', component: PageNotFoundComponent}
];
```
It looks like the Schematics can't handle this configuration.

**Comment by Splaktar** [comment]
However, even changing to the most simple setup gives the same error:
```ts
RouterModule.forRoot([
      {
        path: '',
        pathMatch: 'full',
        component: AboutComponent,
        children: []
      },
      {path: '**', component: PageNotFoundComponent}
    ]),
```

**Comment by Splaktar** [comment]
This appears to be caused by `fs_extra_1.pathExists is not a function`. I found the docs [here](https://github.com/jprichardson/node-fs-extra/blob/master/docs/pathExists.md), but they don't help explain why this wouldn't be a function.

**Comment by Splaktar** [comment]
`npm ls fs-extra` gives me
```
├─┬ firebase-tools@7.10.0
│ ├── fs-extra@0.23.1 
│ └─┬ superstatic@6.0.4
│   └── fs-extra@0.30.0 
└─┬ karma@4.4.1
  └─┬ log4js@4.5.1
    └─┬ streamroller@1.0.6
      └── fs-extra@7.0.1 
```
But nothing from Scully. `pathExists` came out in `fs-extra` `6.0.0`, so if it is using the `fs-extra` from `firebase-tools`, it won't exist. But if it gets the one from `karma`, it should...

**Comment by Splaktar** [comment]
Adding `"fs-extra": "^8.1.0",` to `devDependencies` works around this issue. It looks like `@scullyio/scully` may need to add this as a dependency.

**Comment by SanderElias** [comment]
Thanks for the PR! Good find.
I still wonder why this doesn't pop up for ourselves tho.

**Comment by Splaktar** [comment]
Not sure. I'm on macOS Catalina running the following
```ts
Angular CLI: 9.0.0-rc.6
Node: 12.13.0
OS: darwin x64

Angular: 9.0.0-rc.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.6
@angular-devkit/build-angular     0.900.0-rc.6
@angular-devkit/build-optimizer   0.900.0-rc.6
@angular-devkit/build-webpack     0.900.0-rc.6
@angular-devkit/core              9.0.0-rc.6
@angular-devkit/schematics        9.0.0-rc.6
@angular/cdk                      9.0.0-rc.5
@angular/fire                     5.2.3
@angular/material                 9.0.0-rc.5
@ngtools/webpack                  9.0.0-rc.6
@schematics/angular               9.0.0-rc.6
@schematics/update                0.900.0-rc.6
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
```
