### ISSUE TITLE
App without Ivy gives error: No provider for IdleMonitorService!

### ISSUE THREAD

**Issue by beeman** [scullyio/scully#29]
First of all: congrats on the release! 🥳 I'm super exited to start exploring and using this, it's something I've been looking out for for a while now!

I'll file some issues and later probably some PR's, here's the first thing I ran into.

## Issue

When creating a new app with the latest version of @angular/cli (8.3.20) it has ivy disabled, this seems to yield this error:

```
ERROR NullInjectorError: StaticInjectorError(AppModule)[AppComponent -> IdleMonitorService]: 
  StaticInjectorError(Platform: core)[AppComponent -> IdleMonitorService]: 
    NullInjectorError: No provider for IdleMonitorService!
    at NullInjector.get (http://localhost:4200/vendor.js:39072:27)
    at resolveToken (http://localhost:4200/vendor.js:53990:24)
    at tryResolveToken (http://localhost:4200/vendor.js:53916:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:53766:20)
    at resolveToken (http://localhost:4200/vendor.js:53990:24)
    at tryResolveToken (http://localhost:4200/vendor.js:53916:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:53766:20)
    at resolveNgModuleDep (http://localhost:4200/vendor.js:64953:29)
    at NgModuleRef_.get (http://localhost:4200/vendor.js:66019:16)
    at resolveDep (http://localhost:4200/vendor.js:66550:45)
```

## Workaround

To get around this error you can enable ivy by adding the following object to `tsconfig.app.json` and `tsconfig.app.json`:

```,
   "angularCompilerOptions": {
     "enableIvy": true
   }
```

Or when you start a new project, generate it with the `enable-ivy` flag:

```
ng new scully-with-ivy --routing --style=scss --enable-ivy true
```

## Repro steps
See [demo](https://github.com/beeman/scully-no-ivy) or:

```
ng new scully-no-ivy --routing --style=scss --enable-ivy false
cd scully-no-ivy
ng add @scullyio/init
ng serve
```

**Comment by SanderElias** [comment]
Right now, we don't have an v8 runtime available. For this to work we need to compile our things with version v8, and we don't have that  bandwidth available right now. We are aware of this, and we will probably have set this up before we go beta.

**Comment by SanderElias** [comment]
I'm going to close this issue for now. This will land before, or pretty soon after we released the beta version. Feel free to reopen/refile when somehow this isn't fixed by then
