### ISSUE TITLE
Using  @angular/pwa with scully

### ISSUE THREAD

**Issue by ganeshsundaram39** [scullyio/scully#416]
### Description
Angular pwa not working for ./ in offline mode but its working for ./index.html
Coming here from [Angular](https://github.com/angular/angular/issues/36152#issuecomment-601723129)

#### 🔬 Minimal Reproduction
repo: https://github.com/ganeshsundaram39/ganeshsundaram39.github.io/tree/scully

not working for
https://ganeshsundaram39.github.io/

but works for
https://ganeshsundaram39.github.io/index.html

#### 💻Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 9.0.6
Node: 12.14.1
OS: win32 x64

Angular: 9.0.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.6
@angular-devkit/build-angular     0.900.6
@angular-devkit/build-optimizer   0.900.6
@angular-devkit/build-webpack     0.900.6
@angular-devkit/core              9.0.6
@angular-devkit/schematics        9.0.6
@ngtools/webpack                  9.0.6
@schematics/angular               9.0.6
@schematics/update                0.900.6
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Scully Version:**

<pre><code>
    "@scullyio/init": "0.0.23",
    "@scullyio/ng-lib": "latest",
    "@scullyio/scully": "latest",
</code></pre>

## 🔥 Exception or Error

<pre><code>
NGSW Debug Info:

Driver state: EXISTING_CLIENTS_ONLY (Degraded due to: Hash mismatch (cacheBustedFetchFromNetwork): https://ganeshsundaram39.github.io/index.html: expected 900c53257790571dcf7663ddaa0ec3feaee62797, got 6b93dcbb09a8e4ea0175bb85cd3bbb08319d3a6b (after cache busting)
Error: Hash mismatch (cacheBustedFetchFromNetwork): https://ganeshsundaram39.github.io/index.html: expected 900c53257790571dcf7663ddaa0ec3feaee62797, got 6b93dcbb09a8e4ea0175bb85cd3bbb08319d3a6b (after cache busting)
    at PrefetchAssetGroup.<anonymous> (https://ganeshsundaram39.github.io/ngsw-worker.js:702:35)
    at Generator.next (<anonymous>)
    at fulfilled (https://ganeshsundaram39.github.io/ngsw-worker.js:323:62))
Latest manifest hash: 6eda801cf9b7eda62d55f8345437c215ae521daa
Last update check: 1m13s12u

=== Version 6eda801cf9b7eda62d55f8345437c215ae521daa ===

Clients: 

=== Idle Task Queue ===
Last update tick: 45s428u
Last update run: 1m14s317u
Task queue:

Debug log:

[1m12s328u] Error(Hash mismatch (cacheBustedFetchFromNetwork): https://ganeshsundaram39.github.io/index.html: expected 900c53257790571dcf7663ddaa0ec3feaee62797, got 6b93dcbb09a8e4ea0175bb85cd3bbb08319d3a6b (after cache busting), Error: Hash mismatch (cacheBustedFetchFromNetwork): https://ganeshsundaram39.github.io/index.html: expected 900c53257790571dcf7663ddaa0ec3feaee62797, got 6b93dcbb09a8e4ea0175bb85cd3bbb08319d3a6b (after cache busting)
    at PrefetchAssetGroup.<anonymous> (https://ganeshsundaram39.github.io/ngsw-worker.js:702:35)
    at Generator.next (<anonymous>)
    at fulfilled (https://ganeshsundaram39.github.io/ngsw-worker.js:323:62)) Error occurred while updating to manifest 28dcf60a1bd07ca5a2bb14ad5febbd8af44fe4ab
[1m12s27u] Error(Hash mismatch (cacheBustedFetchFromNetwork): https://ganeshsundaram39.github.io/index.html: expected 900c53257790571dcf7663ddaa0ec3feaee62797, got 6b93dcbb09a8e4ea0175bb85cd3bbb08319d3a6b (after cache busting), Error: Hash mismatch (cacheBustedFetchFromNetwork): https://ganeshsundaram39.github.io/index.html: expected 900c53257790571dcf7663ddaa0ec3feaee62797, got 6b93dcbb09a8e4ea0175bb85cd3bbb08319d3a6b (after cache busting)
    at PrefetchAssetGroup.<anonymous> (https://ganeshsundaram39.github.io/ngsw-worker.js:702:35)
    at Generator.next (<anonymous>)
    at fulfilled (https://ganeshsundaram39.github.io/ngsw-worker.js:323:62)) initializeFully for 6eda801cf9b7eda62d55f8345437c215ae521daa
</code></pre>

**Comment by Splaktar** [comment]
Did you get this working? I'm also seeing issues with `@angular/service-worker` and Scully when offline. I get an infinite loop of the service working sending requests that fail and then reloading the page.
