### ISSUE TITLE
Integrate with @angular/service-worker or add a plugin to support it

### ISSUE THREAD

**Issue by Splaktar** [scullyio/scully#529]
# 🧩 Feature request
There are two major blockers that I've found to using `@angular/service-worker` with Scully to create a PWA:

## Hash mismatch
During `ng build --prod`, the `dist/app/ngsw.json` file gets populated with a `hashTable` object like the following:
```json
hashTable: {
    "/index.html": "e823a8f72a2b9f85dc9b38252d1a366f36fb7dca",
}
```
When `npm run scully` is run, Scully changes that `index.html` by injecting the pre-rendered content into it. But this changes the file's hash.

After the site is deployed and loaded, the service worker will load things just fine. But as part of this, it loads the `ngsw.json` that contains the out of date hash. 

When you go offline and reload, the service worker will return a `504` error due to the cache mismatch. This causes Chrome to enter an infinite loop where it tries to load the `index.html` from the service worker, gets a `504`, tries the network, figures out its offline, tries the service worker instead, gets a `504`... repeat forever.

If you open up `/ngsw/state`, you will see something like this:
```js
NGSW Debug Info:

Driver state: EXISTING_CLIENTS_ONLY 
(Degraded due to: Hash mismatch (cacheBustedFetchFromNetwork): 
https://www.devintent.com/index.html: expected e823a8f72a2b9f85dc9b38252d1a366f36fb7dca, got adc7d92a36aefb2a9d187fc8587e7ef59811ea45 (after cache busting)
Error: Hash mismatch (cacheBustedFetchFromNetwork): 
https://www.devintent.com/index.html: expected e823a8f72a2b9f85dc9b38252d1a366f36fb7dca, got adc7d92a36aefb2a9d187fc8587e7ef59811ea45 (after cache busting)
    at PrefetchAssetGroup.<anonymous> (https://www.devintent.com/ngsw-worker.js:734:35)
    at Generator.next (<anonymous>)
    at fulfilled (https://www.devintent.com/ngsw-worker.js:174:62))
Latest manifest hash: fe1d6f7d8b3cbeb0cc699cbf12d22657aefd17db
Last update check: 27s489u

=== Version fe1d6f7d8b3cbeb0cc699cbf12d22657aefd17db ===
```

To solve this, Scully (or a plugin) would need to regenerate the `index.html`'s hash after pre-rendering and update it in the `dist/static/ngsw.json`.

## Blog Content is generated after the ngsw.json

The `ngsw.json` file that holds your service worker configuration is built during `ng build --prod`. So it has no idea about the routes and files that will be generated by `npm run scully`.

However, once Scully is done with its generation, it (or a plugin) has all of the information that it needs to write those file routes to the `ngsw.json` along with their hashes.

## Documentation

Until this is supported, it may be worth clearly documenting that Scully does not support `@angular/service-worker` or `@angular/pwa`.

**Comment by Splaktar** [comment]
From @SteveDa79131270_twitter on Gitter:
```sh
"pwa:regenerate": "rm dist/static/ngsw.json;node_modules/.bin/ngsw-config dist/static ./ngsw-config.json"
```
> this regenerates the pwa hashes after scully has generated the new files
> then they are available in the service worked offline and updates work!

**Comment by Splaktar** [comment]
This workaround mostly works for me. It gets my site working cached and working offline. The only issue that I have is that reloading when offline only works for my routes without `<scully-content>`. But if I reload on my home page or `/blog` page, it works fine, then I can go to any of the blog posts that I've already visited (lazy caching) and they work offline (as long as I don't reload on a blog page).

Here's the updates that I had to make for my `ngsw-config.json`:
```json
    {
      "name": "blog",
      "installMode": "lazy",
      "updateMode": "prefetch",
      "resources": {
        "files": ["/blog/**/*.html"],
        "urls": ["https://avatars*.githubusercontent.com/**/*", "https://cdn-images-1.medium.com/**/*", "https://miro.medium.com/**/*"]
      }
    }
  ],
  "navigationUrls": ["/**", "!/**/*.*", "!/**/*__*", "!/**/*__*/**"]
```
This caches all of my `index.html` files that Scully generated along with all of the various CDNs where some of my blog post images are hosted.

**Comment by Splaktar** [comment]
https://github.com/angular/angular/issues/16051 seems to be the cause of the offline reload issues in SW. In addition to adding `/index.html` to the route causing it to work, you can also just add `/` to the route to make the offline reload and SW cache lookup work.

Firebase Hosting has a setting for setting `"trailingSlash": true` as well, but Angular always comes in an removes the trailing slash.

There are some workarounds in the above issue that I need to investigate and try out. It looks like providing a custom `UrlSerializer` via `{ provide: UrlSerializer, useClass: CustomUrlSerializer }` is the latest and most appropriate approach.

**Comment by Splaktar** [comment]
The best `UrlSerializer` that I could found was the following
```ts
import { DefaultUrlSerializer, UrlTree } from '@angular/router';

/**
 * @see https://github.com/angular/angular/issues/16051
 */
export class TrailingSlashUrlSerializer extends DefaultUrlSerializer {

  private static _withTrailingSlash(url: string): string {
    const splitOn = url.indexOf('?') > - 1 ? '?' : '#';
    const pathArr = url.split(splitOn);

    if (!pathArr[0].endsWith('/')) {
      let fileName: string = url.substring( url.lastIndexOf('/') + 1);
      if (fileName.indexOf('.') === -1) {
        pathArr[0] += '/';
      }
    }
    const result = pathArr.join(splitOn);
    // console.log(`Result: ${result}`);
    return result;
  }

  serialize(tree: UrlTree): string {
    return TrailingSlashUrlSerializer._withTrailingSlash(super.serialize(tree));
  }
}
```
And it does seem to work in that all URLs get a trailing slash. However, I haven't been able to update my routes, `[routerLink]`, or Scully config to work with this. I tried many different alternatives for a couple of hours.

It seems like no matter what I do, Scully generates the routes without a trailing slash. 
```json
    "route": "/blog/2016-06-28-responsive-ui-angularjs-material",
```
Then when it comes time to lookup a route with a trailing slash, it can't be resolved.

I tried using Firebase Hosting's local emulator with all kinds of different rewrite rules, but I couldn't quite find the magical incantation to make this all work. Thus I couldn't even get to the point of testing this in a Service Worker. 😞

**Comment by SanderElias** [comment]
@Splaktar We have a plugin that will update the routes in the static HTML. 
When you use the render plugin `seoHrefOptimise` in your `defaultPostRenderers` array, all known routes will be updated in the static HTML. This helps with SEO optimization mostly.

**Comment by raphaelApard** [comment]
Hi,

I am trying to achieve something similar to @Splaktar. With TrailingSlashUrlSerializer and seoHrefOptimise as the defaultPostRenderer for Scully, it works fine, but when I go directly to https://mysite/an-url/ the homepage shows up quickly before the real page appears. And this only happens with part of the browser cache because it does not happen in the new incognito window.
I don't understand what's going on here, anyone have any idea about this?

**Comment by kananlanginhooper** [comment]
No idea if this will help, but check your redirect settings on your
hosting.  Regular angular hosting everything that's not an asset (img, css,
js) gets redirected to index.html.  if that is still enabled, you'll see
exactly what you're describing.

**Comment by raphaelApard** [comment]
I'm using nginx with : try_files $uri $uri/ /index.html;

**Comment by SanderElias** [comment]
@raphaelApard It just occured to me that your SW might be serving the 'original' index.html instead of the Scully generated one?

**Comment by PkerUNO** [comment]
@SanderElias I'm not really up to speed with Angular Service Workers but I'm trying to get a Scully site working with PWA and encountering the same issues as the rest of the thread. Going to a deep link in my site directly seems to load the correct template for that page, but examining the Network tab shows that the service worker is loading the main index.html and resources instead, so the data.json the deep linked page receives doesn't contain the data it needs.

Adding ?ngsw-bypass to the end of the URL deactivates the service worker on that load and the page loads correctly. I'm currently trying to figure out if we can modify the service worker to fix this but like I said, I'm no expert.

**Comment by raphaelApard** [comment]
I confirm that adding ?ngsw-bypass remove the first load of the main index.html
This problem happens only when the service worker is enabled. 

If i unregister service worker and access to /some-page/. I don't see the homepage appear. But atfer a second refresh (with fresh registered service worker, i see the homepage appear 1sec before the right page.

**Comment by chrisguttandin** [comment]
I might be wrong, but I think the problem is exactly the opposite of what is described [here](https://github.com/scullyio/scully/issues/529#issuecomment-750208587). Angular's Service Worker uses the `index.html` file in the root directory as the basis for every route. If that file is pre-rendered the content of the home page will be visible for a split second until Angular dynamically rendered the requested route.

I solved this problem by copying the index.html file before pre-rendering it's content. I additionally modified the `ngsw.json` file used by the Service Worker to point it to the un-rendered copy. The implementation is currently part of [angular-prerender](https://github.com/chrisguttandin/angular-prerender) but since angular-prerender does now also support Scully plugins we could re-implement it as a Scully plugin to make it usable with Scully as well.

Back then when I added that feature to angular-prerender I also wrote [an article which explains it a bit more detailed](https://media-codings.com/articles/building-static-but-progressive-web-apps-with-angular). The blog itself is a live demo of the feature. :-)

**Comment by PkerUNO** [comment]
@chrisguttandin Thanks for that, I'll take a look and digest it later. For the time being I "solved" my issue by setting `"navigationRequestStrategy": "freshness"` in ngsw-config.json which as I understand it means it'll only ever use the prerendered pages if the user's connection is offline, otherwise it'll grab it from the server.
