### ISSUE TITLE
getting error while serving angular universal app locally using firebase serve

### ISSUE THREAD

**Issue by MUKESHBEHERA76** [scullyio/scully#642]
mukeshkumarbehera@Mukeshs-MacBook-Air functions % firebase serve

=== Serving from '/Users/mukeshkumarbehera/Desktop/myWebsite/SSR/programingwizard'...

⚠  Your requested "node" version "8" doesn't match your global version "12"
i  functions: Watching "/Users/mukeshkumarbehera/Desktop/myWebsite/SSR/programingwizard/functions" for Cloud Functions...
⚠  hosting: Port 5000 is not available. Trying another port...
i  hosting: Serving hosting files from: dist/programingwizard/browser
✔  hosting: Local server: http://localhost:5005
⚠  Error: Cannot find module '/Users/mukeshkumarbehera/Desktop/myWebsite/SSR/programingwizard/functions/dist/server'
Require stack:
- /Users/mukeshkumarbehera/Desktop/myWebsite/SSR/programingwizard/functions/lib/index.js
- /usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/mukeshkumarbehera/Desktop/myWebsite/SSR/programingwizard/functions/lib/index.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
⚠  We were unable to load your functions code. (see above)
   - It appears your code is written in Typescript, which must be compiled before emulation.
   - You may be able to run "npm run build" in your functions directory to resolve this.

**Comment by SanderElias** [comment]
Closing, as it is not relevant to this repo.
